apiVersion: v1
kind: Pod
metadata:
  name: jenkins.localhost
  labels:
    app: jenkins-app
  namespace: development
spec:
  containers:
    - name: jenkins
      image: jenkins/jenkins:lts-alpine
      ports:
        - containerPort: 8080
